raceme=window.raceme={_idgen:0};function main(a){"undefined"===typeof _main_scripts?_main_scripts=[a]:_main_scripts.push(a)}by=raceme.by=function(a){if("string"!==typeof a)return new GrapeGroup;var c=a.split(":"),d=c[0];return 2==c.length&&"id"==raceme._clearString(d)?(a=c[1],null!==document.getElementById(a)?new Grape(document.getElementById(a)):null):(new Grape(document.documentElement)).by(a)};raceme.addChild=function(a){return(new Grape(document.documentElement)).addChild(a)};
raceme.ajax=function(a){if("object"===typeof a){a.url=raceme.dV(a.url,"http://localhost/");"POST"!=a.method&&"HEAD"!=a.method&&(a.method="GET");a.data=raceme.dV(a.data,"");"XML"!=a.format&&"blob"!=a.format&&(a.format="text");var c;c=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");"string"!==typeof a.data&&(a.data=a.data.toString());"GET"==a.method&&""!=a.data&&(a.url+="?"+a.data);"XML"==a.format&&c.overrideMimeType?c.overrideMimeType("text/xml"):"XML"==a.format?a.format=
"text":"blob"==a.format&&(c.responseType="blob");c.open(a.method,a.url,!0);var d=this;c.onreadystatechange=function(){4==c.readyState&&("undefined"!==typeof a.always&&a.always.call(d),200==c.status||304==c.status?"undefined"!==typeof a.done&&("XML"==a.format&&null!=c.responseXML?(c.responseXML.xml&&a.done.call(d,c.responseXML.xml,"XML"),a.done.call(d,c.responseXML,"XML")):"blob"==a.format?a.done.call(d,c.response):a.done.call(d,c.responseText,"text")):"undefined"!==typeof a.fail&&a.fail.call(d,c.status))};
"POST"!=a.method&&"HEAD"!=a.method||""==a.data?c.send():c.send(a.data);return c}return null};
raceme.label=function(a,c,d,f,e,h,g,k){a=raceme.dV(a,"");"string"!==typeof a&&a.toString&&(a=a.toString());c=raceme.dV(c,0);d=raceme.dV(d,0);f=raceme.dV(f,"black");e=raceme.dV(e,14);h=raceme.dV(h,"left");g=raceme.dV(g,"top");k=raceme.dV(k,1);var l=new Grape("text");l.attr("x",c).attr("y",d).attr("font-size",e);"black"!=f&&l.attr("fill",f);"center"==raceme._clearString(h)&&l.attr("text-anchor","middle");"right"==raceme._clearString(h)&&l.attr("text-anchor","end");1!=k&&l.attr("opacity",k);f=d=0.25*
e;"bottom"==raceme._clearString(g)&&(f=e);"middle"==raceme._clearString(g)&&(f=0.4*e);a=a.split("\n");for(g=0;g<a.length;g++)h=new Grape("tspan"),h.attr("x",c),h.attr("dy",f),"\\b"==a[g].substring(0,2)&&(a[g]=a[g].substring(2),h.attr("fill","rgb(150,150,150)")),h.seed.appendChild(document.createTextNode(a[g])),l.addChild(h),f=e+d;return l};
raceme.image=function(a,c,d,f,e){a=raceme.dV(a,"");c=raceme.dV(c,0);d=raceme.dV(d,0);f=raceme.dV(f,"");e=raceme.dV(e,"");a=(new Grape("image")).attr("href",a).attr("x",c).attr("y",d).attr("width",f).attr("height",e);""===f&&a.load(function(a){this.width(a.target.width)});""===e&&a.load(function(a){this.height(a.target.height)});return a};raceme.wheelValue=function(a){return a.wheelDelta?a.wheelDelta/120:a.detail?-a.detail:0};
raceme.cursorPoint=function(a){var c=a.currentTarget;1!=c.nodeType&&(c=a.target);var d=c.ownerSVGElement.createSVGPoint();d.x=a.clientX;d.y=a.clientY;return d.matrixTransform(c.ownerSVGElement.getScreenCTM().inverse())};raceme.window={};raceme.window.width=function(){return document.documentElement.clientWidth};raceme.window.height=function(){return document.documentElement.clientHeight};function GrapeGroup(){this._items=[];this.length=0;this._animations=[];this._img=null}GrapeGroup.fn=GrapeGroup.prototype;
function Grape(a,c){var d;this.isShape=!1;a=raceme.dV(a,"g");null===a&&(a="g");c=raceme.dV(c,"svg");if("string"===typeof a){if("img"==a||"div"==a)c="html";this.seed="svg"==c?document.createElementNS("http://www.w3.org/2000/svg",a):document.createElement(a);d=this.tagName();if("svg"==d)this.style("overflow","hidden"),this.attr("viewBox","0 0 500 500").attr("width","500").attr("height","500").attr("version","1.1").attr("xmlns","http://www.w3.org/2000/svg").attr("xmlns:xlink","http://www.w3.org/1999/xlink");
else if("circle"==d||"ellipse"==d||"rect"==d||"line"==d||"path"==d||"polygon"==d||"polyline"==d||"image"==d||"text"==d)this.isShape=!0}else{if("undefined"!==typeof a._grape&&a._grape instanceof Grape)return a._grape;this.seed=a;d=a.tagName;if("circle"==d||"ellipse"==d||"rect"==d||"line"==d||"path"==d||"polygon"==d||"polyline"==d||"image"==d||"text"==d)this.isShape=!0}this.seed._grape=this;this.is_beginFill=!1;this.current_fill_color="none";this.current_fill_alpha=1;this.is_beginPath=!1;this.current_path=
"";this.is_beginPath_closed=!1;this.current_stroke_thickness=0;this.current_stroke_color="none";this.current_stroke_caps="butt";this.current_stroke_joints="miter";this.current_stroke_miterLimit=4;this.current_stroke_alpha=1;this.current_stroke_dasharray="1";this.currentY=this.currentX=0;this._animations=[];this._events=[];this._prev_display=null}Grape.fn=Grape.prototype;
function GrapeEvent(a,c,d){this._function=c;this._type=a;d=raceme.dV(d,"none");"string"!==typeof d&&(d=d.toString());this._id=d}
GrapeGroup.fn.by=function(a){if(0==this.length||"string"!==typeof a)return new GrapeGroup;a=a.split(":");var c=new GrapeGroup,d=a[0],d=raceme._clearString(d);if(1==a.length)this.each(function(){raceme._clearString(this.tagName())==d&&c.push(this)});else if(2==a.length){if("id"==d)return raceme.by("id:"+a[1]);var f=raceme._clearString(a[1]);this.each(function(){"class"==d?this.containsClass(f)&&c.push(this):raceme._clearString(this.attr(d))==f&&c.push(this)})}return c};
Grape.fn.by=function(a){if("string"!==typeof a)return new GrapeGroup;a=a.split(":");var c=new GrapeGroup,d=a[0];if(1==a.length){a=this.seed.getElementsByTagName(d);for(var f=0;f<a.length;f++)c.push(new Grape(a[f]))}else if(2==a.length){var e=a[1];if("id"==raceme._clearString(d))return raceme.by("id:"+e);e=raceme._clearString(e);a=this.getChildren();a.each(function(){"class"==raceme._clearString(d)?this.containsClass(e)&&c.push(this):raceme._clearString(this.attr(d))==e&&c.push(this);c.push(this.by(d+
":"+e))})}return c};GrapeGroup.fn.show=function(){return this.each(Grape.fn.show)};Grape.fn.show=function(){"none"==this.style("display")&&(null!==this._prev_display?this.style("display",this._prev_display):this.style("display","inline"));return this};GrapeGroup.fn.hide=function(){return this.each(Grape.fn.hide)};Grape.fn.hide=function(){"none"!=this.style("display")&&(this._prev_display=this.style("display"),this.style("display","none"));return this};
GrapeGroup.fn.attr=function(){if("undefined"===typeof arguments[0])return this;if("undefined"!==typeof arguments[1])return!1===raceme._likeArray(arguments[1])?this.each(Grape.fn.attr,arguments):this.eachValue(Grape.fn.attr,arguments[1],arguments[0]);var a=[];this.each(function(c){a.push(this.attr(c))},arguments);return a};
Grape.fn.attr=function(a,c){if("undefined"!==typeof a&&1==this.seed.nodeType){if("undefined"===typeof c)return!1==this.hasAttr(a)?"undefined"!==typeof raceme._defaultAttributeValues[a]?raceme._defaultAttributeValues[a]:"":"href"!=a||"image"!=this.tagName()&&"filter"!=this.tagName()&&"textPath"!=this.tagName()?this.seed.getAttributeNS(null,a):this.seed.getAttributeNS("http://www.w3.org/1999/xlink",a);""===c||null===c?this.seed.removeAttribute(a):"href"!=a||"image"!=this.tagName()&&"filter"!=this.tagName()&&
"textPath"!=this.tagName()?this.seed.setAttribute(a,c):this.seed.setAttributeNS("http://www.w3.org/1999/xlink",a,c)}return this};GrapeGroup.fn.opacity=function(){return this._applyFunction(Grape.fn.opacity,arguments)};Grape.fn.opacity=function(a){"undefined"!==typeof a&&(a=Math.max(Math.min(a,1),0));return this.style("opacity",a)};GrapeGroup.fn.fill=function(){return this._applyFunction(Grape.fn.fill,arguments)};
Grape.fn.fill=function(a){if("undefined"===typeof a)return this.style("fill");this.seed.style.fill=a;return this};GrapeGroup.fn.width=function(){return this._applyFunction(Grape.fn.width,arguments)};Grape.fn.width=function(a){return this.attr("width",a)};GrapeGroup.fn.height=function(){return this._applyFunction(Grape.fn.height,arguments)};Grape.fn.height=function(a){return this.attr("height",a)};GrapeGroup.fn.zoomable=function(){return this._applyFunction(Grape.fn.zoomable,arguments)};
Grape.fn.zoomable=function(a,c,d){this._zoomable=!0;this._zoom_w=raceme.dV(a,100);this._zoom_h=raceme.dV(c,100);this._zoom_max=raceme.dV(d,5);this._zoom_factor=0.25;this._current_zooming=!1;this._nonscalables=this.by("class:nonscalable");this.endZoom=this.startZoom=this.changePanning=this.endPanning=this.startPanning=null;a=(new Grape("rect")).opacity(0).x(0).y(0).attr("width",this._zoom_w).attr("height",this._zoom_h);this.addChild(a);a.toBack();var f=this;a.drag(function(a){f._startPanning(a)},function(a){f._changePanning(a)},
function(a){f._endPanning(a)}).mousewheel(function(a){f._scrollMouse(a);a.prevenDefault();return!1});return this};GrapeGroup.fn.zoomIn=function(){return this.each(Grape.fn.zoomIn)};Grape.fn.zoomIn=function(){this.setZoom(this.scale()+this._zoom_factor);return this};GrapeGroup.fn.zoomOut=function(){return this.each(Grape.fn.zoomOut)};Grape.fn.zoomOut=function(){this.setZoom(this.scale()-this._zoom_factor);return this};GrapeGroup.fn.setZoom=function(){return this._applyFunction(Grape.fn.setZoom,arguments)};
Grape.fn.setZoom=function(a,c){c=raceme.dV(c,!0);var d=Math.max(1,Math.min(this._zoom_max,a));if(d!=this.scale()){null!==this.startZoom&&this.startZoom.call(this);this._zoom_factor=0.25+0.1*(d-1);var f=this._zoom_w/2-d*((this._zoom_w/2-this.x())/this.scale()),e=this._zoom_h/2-d*((this._zoom_h/2-this.y())/this.scale()),f=Math.max(f,-(this._zoom_w*d)+this._zoom_w),f=Math.min(f,0),e=Math.max(e,-(this._zoom_h*d)+this._zoom_h),e=Math.min(e,0),h=this;1E4>this._nonscalables.length&&c?(this._current_zooming=
!0,this.animate(400).ease("out").move(f,e).scale(d).done(function(){null!==h.endZoom&&h.endZoom.call(this);this._current_zooming=!1}),this._nonscalables.animate(400).ease("out").scale(1/d)):(this.move(f,e).scale(d),this._nonscalables.scale(1/d),null!==this.endZoom&&this.endZoom.call(this))}return this};GrapeGroup.fn.getChildren=function(){var a=new GrapeGroup;this.each(function(){a.push(this.getChildren())});return a};
Grape.fn.getChildren=function(){for(var a=new GrapeGroup,c=this.seed.firstChild;c;)1==c.nodeType&&a.push(new Grape(c)),c=c.nextSibling;return a};GrapeGroup.fn.first=GrapeGroup.fn.firstChild=function(){return this.firstItem().firstChild()};Grape.fn.first=Grape.fn.firstChild=function(){return this.getChildren().firstItem()};GrapeGroup.fn.last=GrapeGroup.fn.lastChild=function(){return this.lastItem().lastChild()};Grape.fn.last=Grape.fn.lastChild=function(){return this.getChildren().lastItem()};
GrapeGroup.fn.getParents=function(){var a=new GrapeGroup;this.each(function(){a.push(this.getParent())});return a};Grape.fn.getParent=function(){return this.seed.parentNode&&"svg"!=this.tagName()&&1==this.seed.nodeType?new Grape(this.seed.parentNode):null};GrapeGroup.fn.remove=function(){return this.each(Grape.fn.remove)};Grape.fn.remove=function(){this.seed.parentNode&&this.seed.parentNode.removeChild(this.seed);return this};GrapeGroup.fn.clear=function(){return this.each(Grape.fn.clear)};
Grape.fn.clear=function(){if("undefined"===typeof this.seed.innerHTML)for(;this.seed.firstChild;)this.seed.removeChild(this.seed.firstChild);else this.seed.innerHTML="";return this};GrapeGroup.fn.toFront=function(){return this.each(Grape.fn.toFront)};Grape.fn.toFront=function(){var a=this.getParent();null!==a&&(a.removeChild(this),a.addChild(this));return this};GrapeGroup.fn.toBack=function(){return this.each(Grape.fn.toBack)};
Grape.fn.toBack=function(){var a=this.getParent();if(null!==a){if(2>a.seed.childNodes.length)return this;a.removeChild(this);a.seed.insertBefore(this.seed,a.seed.childNodes.item(0))}return this};GrapeGroup.fn.x=function(){return this._applyFunction(Grape.fn.x,arguments)};Grape.fn.x=function(a){return this.transform("x",a)};GrapeGroup.fn.y=function(){return this._applyFunction(Grape.fn.y,arguments)};Grape.fn.y=function(a){return this.transform("y",a)};
GrapeGroup.fn.move=function(){return this._applyFunction(Grape.fn.move,arguments)};Grape.fn.move=function(a,c){return 2!=arguments.length?this:this.x(a).y(c)};GrapeGroup.fn.scale=function(){return this._applyFunction(Grape.fn.scale,arguments)};Grape.fn.scale=function(a){this.scalex(a);return this.scaley(a)};GrapeGroup.fn.scalex=function(){return this._applyFunction(Grape.fn.scalex,arguments)};Grape.fn.scalex=function(a){return this.transform("scalex",a)};
GrapeGroup.fn.scaley=function(){return this._applyFunction(Grape.fn.scaley,arguments)};Grape.fn.scaley=function(a){return this.transform("scaley",a)};GrapeGroup.fn.rotation=function(){return this._applyFunction(Grape.fn.rotation,arguments)};Grape.fn.rotation=function(a){return this.transform("rotation",a)};GrapeGroup.fn.rotationcx=function(){return this._applyFunction(Grape.fn.rotationcx,arguments)};Grape.fn.rotationcx=function(a){return this.transform("rotationcx",a)};
GrapeGroup.fn.rotationcy=function(){return this._applyFunction(Grape.fn.rotationcy,arguments)};Grape.fn.rotationcy=function(a){return this.transform("rotationcy",a)};GrapeGroup.fn.skewx=function(){return this._applyFunction(Grape.fn.skewx,arguments)};Grape.fn.skewx=function(a){return this.transform("skewx",a)};GrapeGroup.fn.skewy=function(){return this._applyFunction(Grape.fn.skewy,arguments)};Grape.fn.skewy=function(a){return this.transform("skewy",a)};
GrapeGroup.fn.text=function(){return this._applyFunction(Grape.fn.text,arguments)};Grape.fn.text=function(a){if("undefined"===typeof a){a=this.seed.childNodes;for(var c="",d=0;d<a.length;d++)3==a.item(d).nodeType?c+=a.item(d).nodeValue:1==a.item(d).nodeType&&(c+=(new Grape(a.item(d))).text());return c}for(d=0;d<this.seed.childNodes.length;d++)3==this.seed.childNodes[d].nodeType&&(this.seed.childNodes[d].nodeValue="");""!=a&&this.seed.appendChild(document.createTextNode(a));return this};
GrapeGroup.fn.search=function(){var a=new GrapeGroup;this.each(function(c,d){this.search(c,d)&&a.push(this)},arguments);return a};Grape.fn.search=function(a,c){return"string"!==typeof a?!1:!0!=c?-1==raceme._clearString(this.text()).search(raceme._clearString(a))?!1:!0:-1==this.text().search(a)?!1:!0};GrapeGroup.fn.ajax=function(){return"undefined"!==typeof arguments[0]?!1===raceme._likeArray(arguments[0])?this.each(Grape.fn.ajax,arguments):this.eachValue(Grape.fn.ajax,arguments[0]):this};
Grape.fn.ajax=function(a){raceme.ajax.call(this,a);return this};GrapeGroup.fn.removeAttr=function(){return this.each(Grape.fn.removeAttr,arguments)};Grape.fn.removeAttr=function(a){"undefined"!==typeof a&&this.hasAttr(a)&&this.seed.removeAttribute(a);return this};Grape.fn.hasAttr=function(a){return this.seed.hasAttribute(a)};
GrapeGroup.fn.style=function(){if("undefined"!==typeof arguments[0]&&"undefined"!==typeof arguments[1])return!1===raceme._likeArray(arguments[1])?this.each(Grape.fn.style,arguments):this.eachValue(Grape.fn.style,arguments[1],arguments[0]);if(null===arguments[0])return this.each(function(){this.style(null)});var a=[];this.each(function(c){a.push(this.style(c))},arguments);return a};
Grape.fn.style=function(a,c){if("undefined"!==typeof a){if(null===a)return this.attr("style",null);a=raceme._clearString(a);if("undefined"===typeof c){var d=raceme._getStyle(this.seed);return"undefined"===typeof d[a]?"":d[a]}null===c&&(c="");this.seed.style.setProperty(a,c.toString(),"")}else return raceme._getStyle(this.seed);return this};GrapeGroup.fn.addTo=function(a){a.addChild(this);return this};Grape.fn.addTo=function(a){a.addChild(this);return this};
GrapeGroup.fn.addClass=function(){return this._applyFunction(Grape.fn.addClass,arguments)};Grape.fn.addClass=function(a){if("undefined"!==typeof a&&null!==a){if(this.seed.classList)return this.seed.classList.add(a),this;!1==this.containsClass(a)&&this.attr("class",this.attr("class")+" "+a)}return this};GrapeGroup.fn.removeClass=function(){return this.each(Grape.fn.removeClass,arguments)};
Grape.fn.removeClass=function(a){if("undefined"===typeof a||null===a)return this.removeAttr("class");if(this.seed.classList)return this.seed.classList.remove(a),this;if(!0==this.containsClass(a)){for(var c=this.attr("class").split(" "),d="",f=0;f<c.length;f++)c[f]!=a&&(d+=" "+c[f]);this.attr("class",d)}return this};GrapeGroup.fn.containsClass=function(a){for(var c=0;c<this.length;c++)if(this._items[c].containsClass(a))return!0;return!1};
Grape.fn.containsClass=function(a){return"undefined"===typeof a?!1:this.seed.classList?this.seed.classList.contains(a):-1!=this.attr("class").split(" ").indexOf(a)?!0:!1};GrapeGroup.fn.getBBox=function(){var a=null,c=null,d=null,f=null;this.each(function(){var e=this.getBBox();null===a?(a=e.x1,c=e.y1,d=e.x2,f=e.y2):(a=Math.min(a,e.x1),c=Math.min(c,e.y1),d=Math.max(d,e.x2),f=Math.max(f,e.y2))});return null===a?{x1:0,y1:0,width:0,height:0,x2:0,y2:0}:{x1:a,y1:c,width:d-a,height:f-c,x2:d,y2:f}};
Grape.fn.getBBox=function(){var a={x:0,y:0,x1:0,y1:0,width:0,height:0,x2:0,y2:0};if(this.seed.getBBox)if(this.seed.ownerSVGElement){var c=this.seed.getBBox();a.x1=this.point(c.x,c.y).x;a.y1=this.point(c.x,c.y).y;a.width=c.width;a.height=c.height;a.x2=a.x1+a.width;a.y2=a.y1+a.height;a.x=a.x1;a.y=a.y1}else c=new Grape("svg"),a=new Grape(this.seed.cloneNode(!0)),c.addTo(by("body").item(0)),c.addChild(a),a=a.getBBox(),c.remove();else a={x:this.seed.offsetLeft,y:this.seed.offsetTop,width:this.seed.offsetWidth,
height:this.seed.offsetHeight},a.x1=a.x,a.y1=a.y,a.x2=a.x1+a.width,a.y2=a.y1+a.height;return a};GrapeGroup.fn.lineStyle=function(){return this.each(Grape.fn.lineStyle,arguments)};
Grape.fn.lineStyle=function(a,c,d,f,e,h,g){if(this.isShape)return null===this.getParent()?this:this.getParent().lineStyle(a,c,d,f,e,h,g);this.current_stroke_thickness=raceme.dV(a,0);this.current_stroke_color=raceme.dV(c,"none");this.current_stroke_caps=raceme.dV(f,"butt");this.current_stroke_joints=raceme.dV(e,"miter");this.current_stroke_miterLimit=raceme.dV(h,4);this.current_stroke_alpha=raceme.dV(d,1);this.current_stroke_dasharray=raceme.dV(g,"1");return this};
GrapeGroup.fn.beginFill=function(){return this.each(Grape.fn.beginFill,arguments)};Grape.fn.beginFill=function(a,c){if(this.isShape&&null===this.getParent())return this;if(this.isShape)return this.getParent().beginFill(a,c);this.is_beginFill=!0;this.current_fill_color=raceme.dV(a,"none");this.current_fill_alpha=raceme.dV(c,1);return"none"==this.current_fill_color?this.endFill():this};GrapeGroup.fn.endFill=function(){return this.each(Grape.fn.endFill)};
Grape.fn.endFill=function(){if(this.isShape)return null===this.getParent()?this:this.getParent().endFill();this.is_beginFill=!1;this.current_fill_color="none";this.current_fill_alpha=1;return this};GrapeGroup.fn.beginPath=function(){return this.each(Grape.fn.beginPath,arguments)};
Grape.fn.beginPath=function(a){if(this.isShape)return null===this.getParent()?this:this.getParent().beginPath(a);this.is_beginPath=!0;this.current_path="";this.currentY=this.currentX=0;this.is_beginPath_closed=raceme.dV(a,!1);return this};GrapeGroup.fn.endPath=function(){return this.each(Grape.fn.endPath)};
Grape.fn.endPath=function(){if(this.isShape)return null===this.getParent()?this:this.getParent().endPath();this.is_beginPath=!1;this.currentX=this.currentX=0;if(""!=this.current_path){this.is_beginPath_closed&&(this.current_path+=" z");var a=new Grape("path");a.attr("d",this.current_path);this._applyStroke(a);this._applyFill(a);return a.addTo(this)}return this};GrapeGroup.fn.moveTo=function(){return this.each(Grape.fn.moveTo,arguments)};
Grape.fn.moveTo=function(a,c){if(this.isShape)return null===this.getParent()?this:this.getParent().moveTo(a,c);a=raceme.dV(a,0);c=raceme.dV(c,0);this.is_beginPath&&(this.current_path=this.current_path+"M "+a+" "+c+" ");this.currentX=a;this.currentY=c;return this};GrapeGroup.fn.lineTo=function(){return this.each(Grape.fn.lineTo,arguments)};
Grape.fn.lineTo=function(a,c){if(this.isShape)return null===this.getParent()?this:this.getParent().lineTo(a,c);a=raceme.dV(a,0);c=raceme.dV(c,0);if(this.is_beginPath)""==this.current_path&&this.moveTo(0,0),this.current_path+="L "+a+" "+c+" ";else{var d=new Grape("line");a!=this.currentX&&c!=this.currentY||d.attr("shape-rendering","crispEdges");d.attr("x1",this.currentX).attr("y1",this.currentY).attr("x2",a).attr("y2",c);this._applyStroke(d);this._applyFill(d);return d.addTo(this)}this.currentX=a;
this.currentY=c;return this};GrapeGroup.fn.line=function(){return this.each(Grape.fn.line,arguments)};Grape.fn.line=function(a,c,d,f){return this.isShape?null===this.getParent()?this:this.getParent().line(a,c,d,f):this.moveTo(a,c).lineTo(d,f)};GrapeGroup.fn.circle=GrapeGroup.fn.ellipse=function(){return this.each(Grape.fn.circle,arguments)};
Grape.fn.circle=Grape.fn.ellipse=function(a,c,d,f){if(this.isShape)return null===this.getParent()?this:Grape.fn.circle.call(this.getParent(),a,c,d,f);if(!this.is_beginPath&&0<arguments.length){var e;1==arguments.length?e=(new Grape("circle")).attr("cx",this.currentX).attr("cy",this.currentY).attr("r",a):2==arguments.length?e=(new Grape("ellipse")).attr("cx",this.currentX).attr("cy",this.currentY).attr("rx",a).attr("ry",c):3==arguments.length?e=(new Grape("circle")).attr("cx",a).attr("cy",c).attr("r",
d):(e=(new Grape("ellipse")).attr("cx",a).attr("cy",c).attr("rx",d),attr("ry",f));this._applyStroke(e);this._applyFill(e);return e.addTo(this)}return this};GrapeGroup.fn.rect=function(){return this.each(Grape.fn.rect,arguments)};
Grape.fn.rect=function(a,c,d,f,e,h){if(this.isShape)return null===this.getParent()?this:Grape.fn.rect.apply(this.getParent(),arguments);if(!this.is_beginPath&&0<arguments.length){var g=new Grape("rect");1==arguments.length?g.attr("x",this.currentX).attr("y",this.currentY).attr("width",a).attr("height",a).attr("shape-rendering","crispEdges"):2==arguments.length?g.attr("x",this.currentX).attr("y",this.currentY).attr("width",a).attr("height",c).attr("shape-rendering","crispEdges"):3==arguments.length?
g.attr("x",a).attr("y",c).attr("width",d).attr("height",d).attr("shape-rendering","crispEdges"):4==arguments.length?g.attr("x",a).attr("y",c).attr("width",d).attr("height",f).attr("shape-rendering","crispEdges"):5==arguments.length?g.attr("x",a).attr("y",c).attr("width",d).attr("height",f).attr("rx",e):g.attr("x",a).attr("y",c).attr("width",d).attr("height",f).attr("rx",e).attr("ry",h);this._applyStroke(g);this._applyFill(g);return g.addTo(this)}return this};
GrapeGroup.fn.arcTo=function(){return this.each(Grape.fn.arcTo,arguments)};Grape.fn.arcTo=function(a,c,d,f,e){if(3>arguments.length)return this;f=raceme.dV(f,0);e=raceme.dV(e,1);this.is_beginPath&&(""==this.current_path&&this.moveTo(0,0),this.current_path+="A "+d+" "+d+" 0 "+f+" "+e+" "+a+" "+c+" ");return this};GrapeGroup.fn.curveTo=function(){return this.each(Grape.fn.curveTo,arguments)};
Grape.fn.curveTo=function(a,c,d,f,e,h){if(6!=arguments.length)return this;this.is_beginPath&&(""==this.current_path&&this.moveTo(0,0),this.current_path+="C "+d+" "+f+" "+e+" "+h+" "+a+" "+c+" ");return this};GrapeGroup.squircle=function(){return this.each(Grape.fn.squircle,arguments)};
Grape.fn.squircle=function(a,c,d,f){if(this.isShape)return null===this.getParent()?this:this.getParent().squircle(a,c,d,f);if(!1==this.is_beginPath){var e=0,h=0,g=0,k=0;if(1==arguments.length)e=this.currentX,h=this.currentY,k=g=a;else if(2==arguments.length)e=this.currentX,h=this.currentY,g=a,k=c;else if(3==arguments.length)e=a,h=c,k=g=d;else if(4==arguments.length)e=a,h=c,g=d,k=f;else return this;this.beginPath();this.moveTo(e,h+k/2);this.curveTo(e+g/2,h+k,e,h+k,e,h+k);this.curveTo(e+g,h+k/2,e+g,
h+k,e+g,h+k);this.curveTo(e+g/2,h,e+g,h,e+g,h);this.curveTo(e,h+k/2,e,h,e,h);return this.endPath()}return this};GrapeGroup.fn.arc=function(){return this.each(Grape.fn.arc,arguments)};
Grape.fn.arc=function(a,c,d,f,e,h){if(this.isShape)return null===this.getParent()?this:this.getParent().arc(a,c,d,f,e,h);if(!this.is_beginPath){a=raceme.dV(a,0);c=raceme.dV(c,0);d=raceme.dV(d,10);f=raceme.dV(f,0);e=raceme.dV(e,360);h=raceme.dV(h,!1);f=Math.max(Math.min(f,360),-360);e=Math.max(Math.min(e,360),-360);0>f&&(f=360-f);0>e&&(e=360-e);if(f>e){var g=f;f=e;e=g}if(360<=e-f)return this.circle(a,c,d);g=0;180<e-f&&(g=1);var k=a+raceme.polar2rect(d,f).x;f=c+raceme.polar2rect(d,f).y;var l=a+raceme.polar2rect(d,
e).x;e=c+raceme.polar2rect(d,e).y;h?(this.beginPath(!0),this.moveTo(a,c).lineTo(k,f).arcTo(l,e,d,g),this.endPath()):this.is_beginFill&&"none"!=this.current_fill_color?(h=this.current_stroke_color,this.current_stroke_color="none",this.beginPath(!0),this.moveTo(a,c).lineTo(k,f).arcTo(l,e,d,g),this.endPath(),this.current_stroke_color=h,this.is_beginFill=!1,this.beginPath(!1),this.moveTo(k,f).arcTo(l,e,d,g),this.endPath(),this.is_beginFill=!0):(this.beginPath(!1),this.moveTo(k,f).arcTo(l,e,d,g),this.endPath())}return this};
GrapeGroup.fn.pieSlice=function(){return this.each(Grape.fn.pieSlice,arguments)};
Grape.fn.pieSlice=function(a,c,d,f,e,h){if(this.isShape)return null===this.getParent()?this:this.getParent().pieSlice(a,c,d,f);if(!this.is_beginPath){a=raceme.dV(a,0);c=raceme.dV(c,0);e=raceme.dV(e,0);h=raceme.dV(h,0);d=raceme.dV(d,0);f=raceme.dV(f,360);d=Math.max(Math.min(d,360),-360);f=Math.max(Math.min(f,360),-360);0>d&&(d=360-d);0>f&&(f=360-end);if(d>f){var g=d;d=f;f=g}0==d&&360==f&&(f=359.99999);g=0;180<f-d&&(g=1);var k=e+raceme.polar2rect(a,d).x,l=h+raceme.polar2rect(a,d).y,m=e+raceme.polar2rect(a,
f).x,n=h+raceme.polar2rect(a,f).y,p=e+raceme.polar2rect(c,d).x;d=h+raceme.polar2rect(c,d).y;e+=raceme.polar2rect(c,f).x;f=h+raceme.polar2rect(c,f).y;this.beginPath(!0);this.moveTo(k,l).arcTo(m,n,a,g).lineTo(e,f).arcTo(p,d,c,g,0);this.endPath()}return this};GrapeGroup.fn.label=function(){return this.each(Grape.fn.label,arguments)};
Grape.fn.label=function(a,c,d,f,e,h,g,k){return this.isShape?null===this.getParent()?this:this.getParent().label(a,c,d,f,e,h,g,k):this.is_beginPath?this:raceme.label(a,c,d,f,e,h,g,k).addTo(this)};GrapeGroup.fn.image=function(){return this.each(Grape.fn.image,arguments)};
Grape.fn.image=function(a,c,d,f,e){return this.isShape?null===this.getParent()?this:this.getParent().image(a,c,d,f,e):"filter"==this.tagName()||null!=this.getParent()&&"filter"==this.getParent().tagName()?this.fe("feImage"):this.is_beginPath?thid:raceme.image(a,c,d,f,e).addTo(this)};GrapeGroup.fn.enableEvents=function(){return this.each(Grape.fn.enableEvents,arguments)};Grape.fn.enableEvents=function(a){return!1===a?this.style("pointer-events","none"):this.style("pointer-events","visible")};
GrapeGroup.fn.addEvent=function(){return this.each(Grape.fn.addEvent,arguments)};
Grape.fn.addEvent=function(a,c,d){if("string"!==typeof a||"undefined"===typeof c)return this;var f=this,e=function(d){"paste"==a?setTimeout(function(){c.call(f,d)},0):c.call(f,d);"mousedown"!=a&&("paste"!=a&&"keypress"!=a&&"keydown"!=a&&"keyup"!=a&&"mousewheel"!=a&&"DOMMouseScroll"!=a&&"mousemove"!=a)&&d.preventDefault()};this._events.push(new GrapeEvent(a,e,d));"load"!=a||"image"!=this.tagName()&&"IMG"!=this.tagName()?this.seed.addEventListener?this.seed.addEventListener(a,e):this.seed.attachEvent&&
this.seed.attachEvent(a,e):(this._img=new Image,this._img.addEventListener?this._img.addEventListener("load",e,!1):this._img.attachEvent&&this._img.attachEvent("load",e,!1),"image"==this.tagName()?this._img.src=this.attr("href"):this._img.src=this.attr("src"),this.seed.src=this._img.src);"mouse_leave"==a?this.seed.addEventListener?this.seed.addEventListener("mouseout",this._onmouseleave):this.seed.attachEvent&&this.seed.attachEvent("mouseout",this._onmouseleave):"mouse_enter"==a&&(this.seed.addEventListener?
this.seed.addEventListener("mouseover",this._onmouseenter):this.seed.attachEvent&&this.seed.attachEvent("mouseover",this._onmouseenter));return this};GrapeGroup.fn.removeEvent=function(){return this.each(Grape.fn.removeEvent,arguments)};
Grape.fn.removeEvent=function(a){for(var c=[],d=0;d<this._events.length;d++)"undefined"===typeof a||null===a||this._events[d]._id==a||this._events[d]._type==a?("load"==this._events[d]._type&&null!=this._img&&this._img.removeEventListener("load",this._events[d]._function),"mouse_leave"==this._events[d]._type&&this.seed.removeEventListener("mouseout",this._onmouseleave),"mouse_enter"==this._events[d]._type&&this.seed.removeEventListener("mouseover",this._onmouseenter),this.seed.removeEventListener(this._events[d]._type,
this._events[d]._function)):c.push(this._events[d]);this._events=c;return this};GrapeGroup.fn.trigger=function(){return this.each(Grape.fn.trigger,arguments)};
Grape.fn.trigger=function(a){if("focus"==a)return this.seed.focus(),this;if("blur"==a&&this.seed.blur)return this.seed.blur(),this;if("click"==a&&this.seed.click)return this.seed.click(),this;a=raceme.dV(a,"");for(var c=0;c<this._events.length;c++)if(""==a||this._events[c]._id==a||this._events[c]._type==a){var d=raceme._newEvent(this._events[c]._type);this.seed.dispatchEvent(d)}return this};GrapeGroup.fn.click=GrapeGroup.fn.clic=function(){return this.each(Grape.fn.click,arguments)};
Grape.fn.click=Grape.fn.clic=function(a,c,d){if(0==arguments.length)return this.trigger("click");d=raceme.dV(d,!0);!0===d&&this.style("cursor","pointer");return this.addEvent("click",a,c)};GrapeGroup.fn.dblclick=GrapeGroup.fn.dblclic=function(){return this.each(Grape.fn.dblclick,arguments)};Grape.fn.dblclick=GrapeGroup.fn.dblclic=function(a,c){if(0==arguments.length)return this.trigger("dblclick");this.style("cursor","pointer");return this.addEvent("dblclick",a,c)};
GrapeGroup.fn.mousedown=function(){return this.each(Grape.fn.mousedown,arguments)};Grape.fn.mousedown=function(a,c){return 0==arguments.length?this.trigger("mousedown"):this.addEvent("mousedown",a,c)};GrapeGroup.fn.touchstart=function(){return this.each(Grape.fn.touchstart,arguments)};Grape.fn.touchstart=function(a,c){return 0==arguments.length?this.trigger("touchstart"):this.addEvent("touchstart",a,c)};GrapeGroup.fn.mouseup=function(){return this.each(Grape.fn.mouseup,arguments)};
Grape.fn.mouseup=function(a,c){return 0==arguments.length?this.trigger("mouseup"):this.addEvent("mouseup",a,c)};GrapeGroup.fn.touchend=function(){return this.each(Grape.fn.touchend,arguments)};Grape.fn.touchend=function(a,c){return 0==arguments.length?this.trigger("touchend"):this.addEvent("touchend",a,c)};GrapeGroup.fn.mousemove=function(){return this.each(Grape.fn.mousemove,arguments)};
Grape.fn.mousemove=function(a,c){return 0==arguments.length?this.trigger("mousemove"):this.addEvent("mousemove",a,c)};GrapeGroup.fn.touchmove=function(){return this.each(Grape.fn.touchmove,arguments)};Grape.fn.touchmove=function(a,c){return 0==arguments.length?this.trigger("touchmove"):this.addEvent("touchmove",a,c)};GrapeGroup.fn.mouseover=function(){return this.each(Grape.fn.mouseover,arguments)};
Grape.fn.mouseover=function(a,c){return 0==arguments.length?this.trigger("mouseover"):this.addEvent("mouseover",a,c)};GrapeGroup.fn.mouseenter=function(){return this.each(Grape.fn.mouseenter,arguments)};Grape.fn.mouseenter=function(a,c){return 0==arguments.length?this.trigger("mouse_enter"):this.addEvent("mouse_enter",a,c)};GrapeGroup.fn.mouseleave=function(){return this.each(Grape.fn.mouseleave,arguments)};
Grape.fn.mouseleave=function(a,c){return 0==arguments.length?this.trigger("mouse_leave"):this.addEvent("mouse_leave",a,c)};GrapeGroup.fn.mouseout=function(){return this.each(Grape.fn.mouseout,arguments)};Grape.fn.mouseout=function(a,c){return 0==arguments.length?this.trigger("mouseout"):this.addEvent("mouseout",a,c)};GrapeGroup.fn.mousewheel=function(){return this.each(Grape.fn.mousewheel,arguments)};
Grape.fn.mousewheel=function(a,c){0==arguments.length&&(this.trigger("mousewheel"),this.trigger("DOMMouseScroll"));this.addEvent("mousewheel",a,c);return this.addEvent("DOMMouseScroll",a,c)};GrapeGroup.fn.drag=function(){return this.each(Grape.fn.drag,arguments)};Grape.fn.drag=function(a,c,d){if("undefined"==typeof a)return this;var f=this;this.touchstart(function(e){a.call(f,e);f._initDrag(e,c,d)});return this.mousedown(function(e){3!=e.which&&(a.call(f,e),f._initDrag(e,c,d))})};
GrapeGroup.fn.change=function(){return this.each(Grape.fn.change,arguments)};Grape.fn.change=function(a,c){return 0==arguments.length?this.trigger("change"):this.addEvent("change",a,c)};GrapeGroup.fn.load=function(){return this.each(Grape.fn.load,arguments)};Grape.fn.load=function(a,c){return 0==arguments.length?this.trigger("load"):this.addEvent("load",a,c)};GrapeGroup.fn.paste=function(){return this.each(Grape.fn.paste,arguments)};
Grape.fn.paste=function(a,c){return 0==arguments.length?this.trigger("paste"):this.addEvent("paste",a,c)};GrapeGroup.fn.blur=function(){return this.each(Grape.fn.blur,arguments)};Grape.fn.blur=function(a,c){return 0==arguments.length?this.trigger("blur"):this.addEvent("blur",a,c)};GrapeGroup.fn.focus=function(){return this.each(Grape.fn.focus,arguments)};Grape.fn.focus=function(a,c){return 0==arguments.length?this.trigger("focus"):this.addEvent("focus",a,c)};
GrapeGroup.fn.keypress=function(){return this.each(Grape.fn.keypress,arguments)};Grape.fn.keypress=function(a,c){return 0==arguments.length?this.trigger("keypress"):this.addEvent("keypress",a,c)};GrapeGroup.fn.keydown=function(){return this.each(Grape.fn.keydown,arguments)};Grape.fn.keydown=function(a,c){return 0==arguments.length?this.trigger("keydown"):this.addEvent("keydown",a,c)};GrapeGroup.fn.keyup=function(){return this.each(Grape.fn.keyup,arguments)};
Grape.fn.keyup=function(a,c){return 0==arguments.length?this.trigger("keyup"):this.addEvent("keyup",a,c)};GrapeGroup.fn.select=function(){return this.each(Grape.fn.select,arguments)};Grape.fn.select=function(a,c){return 0==arguments.length?this.trigger("select"):this.addEvent("select",a,c)};GrapeGroup.fn.input=function(){return this.each(Grape.fn.input,arguments)};Grape.fn.input=function(a,c){return 0==arguments.length?this.trigger("input"):this.addEvent("input",a,c)};
GrapeGroup.fn.scroll=function(){return this.each(Grape.fn.scroll,arguments)};Grape.fn.scroll=function(a,c){return 0==arguments.length?this.trigger("input"):this.addEvent("scroll",a,c)};GrapeGroup.fn.error=function(){return this.each(Grape.fn.error,arguments)};Grape.fn.error=function(a,c){return 0==arguments.length?this.trigger("input"):this.addEvent("error",a,c)};GrapeGroup.fn.animate=function(a,c){var d=new AnimationGroup(this,a,c);this._animations.push(d);return d};
Grape.fn.animate=function(a,c){var d=new GrapeAnimation(this,a,c);this._animations.push(d);return d};GrapeGroup.fn.delay=function(a){return this.animate(0,a)};Grape.fn.delay=function(a){return this.animate(0,a)};GrapeGroup.fn.ease=function(){return this.eachAnimation(AnimationGroup.fn.ease,arguments)};Grape.fn.ease=function(){return this.eachAnimation(GrapeAnimation.fn.ease,arguments)};GrapeGroup.fn.stop=function(){return this.eachAnimation(AnimationGroup.fn.stop)};Grape.fn.stop=function(){return this.eachAnimation(GrapeAnimation.fn.stop)};
GrapeGroup.fn.restart=function(){return this.eachAnimation(AnimationGroup.fn.restart)};Grape.fn.restart=function(){return this.eachAnimation(GrapeAnimation.fn.restart)};GrapeGroup.fn.pause=function(){return this.eachAnimation(AnimationGroup.fn.pause,arguments)};Grape.fn.pause=function(){return this.eachAnimation(GrapeAnimation.fn.pause,arguments)};GrapeGroup.fn.resume=function(){return this.eachAnimation(AnimationGroup.fn.resume)};Grape.fn.resume=function(){return this.eachAnimation(GrapeAnimation.fn.resume)};
GrapeGroup.fn.togglePause=function(){return this.eachAnimation(AnimationGroup.fn.togglePause)};Grape.fn.togglePause=function(){return this.eachAnimation(GrapeAnimation.fn.togglePause)};GrapeGroup.fn.item=function(a){return 0==this.length?null:"undefined"===typeof a?this.item(this.length-1):0<=a&&a<this.length?this._items[a]:null};GrapeGroup.fn.each=function(a,c){for(var d=0;d<this.length;d++)a.apply(this._items[d],c);return this};GrapeGroup.fn.sort=function(a){this._items.sort(a);return this};
GrapeGroup.fn.eachValue=function(a,c,d){if("undefined"===typeof d)for(var f=0;f<this.length&&f<c.length;f++)a.call(this._items[f],c[f]);else for(f=0;f<this.length&&f<c.length;f++)a.call(this._items[f],d,c[f]);return this};GrapeGroup.fn.eachAnimation=function(a,c){for(var d=0;d<this._animations.length;d++)a.apply(this._animations[d],c);return this};GrapeGroup.fn.lastItem=function(){return this.item()};GrapeGroup.fn.firstItem=function(){return this.item(0)};
GrapeGroup.fn.push=function(a){if("undefined"===typeof a)return this;if("undefined"!==typeof a._items)for(var c=0;c<a.length;c++)this.push(a._items[c]);else this._items.push(a),this.length++;return this};GrapeGroup.fn._applyFunction=function(a,c){if("undefined"!==typeof c[0])return!1===raceme._likeArray(c[0])?this.each(a,c):this.eachValue(a,c[0]);var d=[];this.each(function(){d.push(a.call(this))});return d};
Grape.fn.save=function(a){a=raceme.dV(a,"svg.svg");var c=document.createElement("a");c.setAttribute("href","data:text/plain;charset=utf-8,"+encodeURIComponent((new XMLSerializer).serializeToString(this.seed)));c.setAttribute("download",a);c.click()};
Grape.fn.addChild=function(a){if(a instanceof Grape)this.seed.appendChild(a.seed);else if(a instanceof GrapeGroup){for(var c=document.createDocumentFragment(),d=0;d<a.length;d++)c.appendChild(a.item(d).seed);this.seed.appendChild(c)}else"string"===typeof a?(window.DOMParser?(c=new DOMParser,c=c.parseFromString(a,"application/xml")):(c=new ActiveXObject("Microsoft.XMLDOM"),c.async=!1,c.loadXML(a)),"svg"==c.documentElement.tagName&&c.documentElement.style.setProperty("overflow","hidden"),this.seed.appendChild(c.documentElement)):
a.nodeType&&(9==a.nodeType?("svg"==a.documentElement.tagName&&a.documentElement.style.setProperty("overflow","hidden"),this.seed.appendChild(a.documentElement)):1==a.nodeType&&("svg"==a.tagName&&a.style.setProperty("overflow","hidden"),this.seed.appendChild(a)));return this};Grape.fn.removeChild=function(a){a instanceof Grape&&this.seed.removeChild(a.seed);return this};
Grape.fn.replace=function(a){a instanceof Grape&&(this.seed.parentNode&&this.seed.parentNode.replaceChild(a.seed,this.seed),this.seed=a.seed,this.seed._grape=this);return this};GrapeGroup.fn.filter=function(){return this.each(Grape.fn.filter,arguments)};
Grape.fn.filter=function(a){if(a instanceof Grape&&"filter"==a.tagName()){var c=a.id();""===c&&(c=raceme._generateId(),a.id(c));this.style("filter","url(#"+c+")")}else"string"===typeof a&&(raceme.by("id:"+a)instanceof Grape&&"filter"==raceme.by("id:"+a).tagName())&&this.style("filter","url(#"+a+")");return this};Grape.fn.fe=function(a){return"filter"===this.tagName()?(new Grape(a)).addTo(this):"filter"===this.getParent().tagName()?(new Grape(a)).addTo(this.getParent()):this};Grape.fn.blend=function(){return this.fe("feBlend")};
Grape.fn.colorMatrix=function(){return this.fe("feColorMatrix")};Grape.fn.componentTransfer=function(){return this.fe("feComponentTransfer")};Grape.fn.funcA=function(){if("feComponentTransfer"===this.tagName())return(new Grape("feFuncA")).addTo(this);"feFunc"===this.tagName().substr(0,this.tagName().length-1)&&"feComponentTransfer"===this.getParent().tagName()&&this.getParent().funcA();return this};
Grape.fn.funcR=function(){if("feComponentTransfer"===this.tagName())return(new Grape("feFuncR")).addTo(this);"feFunc"===this.tagName().substr(0,this.tagName().length-1)&&"feComponentTransfer"===this.getParent().tagName()&&this.getParent().funcR();return this};
Grape.fn.funcG=function(){if("feComponentTransfer"===this.tagName())return(new Grape("feFuncG")).addTo(this);"feFunc"===this.tagName().substr(0,this.tagName().length-1)&&"feComponentTransfer"===this.getParent().tagName()&&this.getParent().funcG();return this};
Grape.fn.funcB=function(){if("feComponentTransfer"===this.tagName())return(new Grape("feFuncB")).addTo(this);"feFunc"===this.tagName().substr(0,this.tagName().length-1)&&"feComponentTransfer"===this.getParent().tagName()&&this.getParent().funcB();return this};Grape.fn.composite=function(){return this.fe("feComposite")};Grape.fn.convolveMatrix=function(){return this.fe("feConvolveMatrix")};Grape.fn.diffuseLighting=function(){return this.fe("feDiffuseLighting")};Grape.fn.displacementMap=function(){return this.fe("feDisplacementMap")};
Grape.fn.flood=function(){return this.fe("feFlood")};Grape.fn.gaussianBlur=function(){return this.fe("feGaussianBlur")};Grape.fn.merge=function(){return this.fe("feMerge")};Grape.fn.morphology=function(){return this.fe("feMorphology")};Grape.fn.offset=function(){return this.fe("feOffset")};Grape.fn.specularLighting=function(){return this.fe("feSpecularLighting")};Grape.fn.tile=function(){return this.fe("feTile")};Grape.fn.turbulence=function(){return this.fe("feTurbulence")};
Grape.fn.mergeNode=function(){return"feMerge"===this.tagName()?(new Grape("feMergeNode")).addTo(this):"feMergeNode"===this.tagName()&&"feMerge"===this.getParent().tagName()?this.getParent().mergeNode():this};
Grape.fn.shadow=function(a,c,d,f){if("filter"===this.tagName())a=raceme.dV(a,0),c=raceme.dV(c,0),d=raceme.dV(d,1),f=raceme.dV(f,1),this.gaussianBlur().attr("in","SourceAlpha").attr("stdDeviation",d),this.offset().attr("dx",a).attr("dy",c).attr("result","offsetblur"),this.componentTransfer().funcA().attr("type","linear").attr("slope",f),this.merge().mergeNode().mergeNode().attr("in","SourceGraphic");else if(this.getParent()&&"filter"===this.getParent().tagName())return this.getParent().shadow(a,c,
d,f);return this};
Grape.fn.getPolygon=function(a){a=raceme.dV(a,!0);var c=new raceme.Polygon;if("path"==this.tagName()){var d=this.seed,f=d.getTotalLength(),e=d.getPointAtLength(0);d.getPathSegAtLength(0);var h=Math.max(parseInt(f/50),1);a?c.add(raceme._elementPoint(this.seed,e.x,e.y)):c.add({x:e.x,y:e.y});for(var g=1;g<f;g+=h)e=d.getPointAtLength(g),a?c.add(raceme._elementPoint(this.seed,e.x,e.y)):c.add({x:e.x,y:e.y})}c.item(0).x==c.item(c.length-1).x&&c.item(0).y==c.item(c.length-1).y||c.add({x:c.item(0).x,y:c.item(0).y});
return c};
Grape.fn.getSubPaths=function(){var a=null,c=null,d=!0,f=[];if("path"==this.tagName())for(var e=this.attr("d"),e=e.split(/z|Z/),h=0;h<e.length-1;h++){f[h]=new raceme.Polygon;e[h]=e[h].split(" ");for(var g=0;g<e[h].length;g++){var k=e[h][g].split(",");if(2==k.length)null===a||!1==d?(a=parseFloat(k[0]),c=parseFloat(k[1])):(a+=parseFloat(k[0]),c+=parseFloat(k[1])),f[h].add({x:a,y:c});else if(1==k.length)if("l"==k[0]||"m"==k[0])d=!0;else if("M"==k[0]||"L"==k[0])d=!1}f[h].item(f[h].length-1).x==f[h].item(0).x&&
f[h].item(f[h].length-1).y==f[h].item(0).y||f[h].add({x:f[h].item(0).x,y:f[h].item(0).y})}return f};raceme.subpaths2path=function(a){for(var c="",d=0,f=0,e=0;e<a.length;e++){for(var c=c+"m ",h=0;h<a[e].length;h++)d=a[e].item(h).x-d,f=a[e].item(h).y-f,c+=viz.Utils.round(d,1)+","+viz.Utils.round(f,1)+" ",d=a[e].item(h).x,f=a[e].item(h).y;c=e==a.length-1?c+"z":c+"z "}return c};Grape.fn.tagName=function(){return this.seed.tagName};Grape.fn.id=function(a){return this.attr("id",a)};
Grape.fn.viewbox=function(a,c,d,f){if("svg"===raceme._clearString(this.tagName())){var e=this.seed.viewBox.baseVal||{x:0,y:0,width:0,height:0};if("undefined"===typeof a)return e;e.x=a;"undefined"!==typeof c&&(e.y=c);"undefined"!=typeof d&&(e.width=d);"undefined"!=typeof f&&(e.height=f);return this.attr("viewBox",e.x+" "+e.y+" "+e.width+" "+e.height)}return this};Grape.fn.point=function(a,c){return raceme._elementPoint(this.seed,a,c)};Grape.fn.selectedIndex=function(){return this.seed.selectedIndex};
Grape.fn.selectedValue=function(){return this.seed.options[this.selectedIndex()].value};Grape.fn.selectedText=function(){return this.seed.options[this.selectedIndex()].text};Grape.fn.enable=function(){this.seed.disabled=!1;return this};Grape.fn.enabled=function(){return!this.seed.disabled};Grape.fn.disable=function(){this.seed.disabled=!0;return this};Grape.fn.disabled=function(){return this.seed.disabled};Grape.fn.checked=function(){return this.seed.checked};
Grape.fn.clearOptions=function(){this.seed.options.length=0;return this};Grape.fn.pushOption=function(a,c){this.seed.options[this.seed.options.length]=new Option(a,c)};Grape.fn.value=function(a){if("undefined"===typeof a)return this.seed.value;this.seed.value=a;return this};GrapeGroup.fn.topOffset=function(){return this._applyFunction(Grape.fn.topOffset,arguments)};
Grape.fn.topOffset=function(a){if("undefined"!==typeof a)this.seed.offsetParent&&(this.seed.offsetParent.scrollTop=this.seed.offsetTop-a);else return this.seed.offsetTop-this.seed.offsetParent.scrollTop};GrapeGroup.fn.scrollTop=function(){return this._applyFunction(Grape.fn.scrollTop,arguments)};Grape.fn.scrollTop=function(a){if("undefined"!==typeof a)this.seed.scrollTop=a;else return this.seed.scrollTop;return this};
Grape.fn.eachAnimation=function(a,c){for(var d=0;d<this._animations.length;d++)a.apply(this._animations[d],c);return this};
Grape.fn._applyStroke=function(a){if(0==this.current_stroke_thickness||"none"==this.current_stroke_color)return this;"none"!=this.current_stroke_color&&a.attr("stroke",this.current_stroke_color);1!=this.current_stroke_thickness&&(a.attr("stroke-width",this.current_stroke_thickness),"butt"!=this.current_stroke_caps&&a.attr("stroke-linecap",this.current_stroke_caps),"miter"!=this.current_stroke_joints&&a.attr("stroke-linejoin",this.current_stroke_joints),4!=this.current_stroke_miterLimit&&a.attr("stroke-miterlimit",
this.current_stroke_miterLimit));1!=this.current_stroke_alpha&&a.attr("stroke-opacity",this.current_stroke_alpha);"1"!=this.current_stroke_dasharray&&a.attr("stroke-dasharray",this.current_stroke_dasharray);return this};Grape.fn._applyFill=function(a){this.is_beginFill&&("none"!=this.current_fill_color&&a.style("fill",this.current_fill_color),1!=this.current_fill_alpha&&a.style("fill-opacity",this.current_fill_alpha));return this};
Grape.fn.transform=function(a,c){"undefined"===typeof this._transform&&(this._transform=raceme._transform2obj(this.attr("transform")));if("undefined"===typeof c)return this._transform[a];c=raceme._round(c,3);if(this._transform[a]==c)return this;this._transform[a]=c;if(this.seed.transform.baseVal&&this.seed.ownerSVGElement){this.seed.transform.baseVal.clear();if(0!=this._transform.x||0!=this._transform.y){var d=this.seed.ownerSVGElement.createSVGTransform();d.setTranslate(this._transform.x,this._transform.y);
this.seed.transform.baseVal.appendItem(d)}if(0!=this._transform.rotation||0!=this._transform.rotationcx||0!=this._transform.rotationcy)d=this.seed.ownerSVGElement.createSVGTransform(),d.setRotate(this._transform.rotation,this._transform.rotationcx,this._transform.rotationcy),this.seed.transform.baseVal.appendItem(d);if(1!=this._transform.scalex||1!=this._transform.scaley)d=this.seed.ownerSVGElement.createSVGTransform(),d.setScale(this._transform.scalex,this._transform.scaley),this.seed.transform.baseVal.appendItem(d);
0!=this._transform.skewx&&(d=this.seed.ownerSVGElement.createSVGTransform(),d.setSkewX(this._transform.skewx),this.seed.transform.baseVal.appendItem(d));0!=this._transform.skewy&&(d=this.seed.ownerSVGElement.createSVGTransform(),d.setSkewY(this._transform.skewy),this.seed.transform.baseVal.appendItem(d))}else this.attr("transform",raceme._obj2transform(this._transform));return this};
Grape.fn._startPanning=function(a){this._panningX=a.clientX;this._panningY=a.clientY;null!==this.startPanning&&this.startPanning.call(this,a);return!1};
Grape.fn._changePanning=function(a){var c=this._panningX-a.clientX,d=this._panningY-a.clientY,c=this.x()-c,d=this.y()-d,c=Math.max(c,-(this._zoom_w*this.scale())+this._zoom_w),c=Math.min(c,0),d=Math.max(d,-(this._zoom_h*this.scale())+this._zoom_h),d=Math.min(d,0);this.move(c,d);this._panningX=a.clientX;this._panningY=a.clientY;null!==this.changePanning&&this.changePanning.call(this,a);return!1};Grape.fn._endPanning=function(a){null!==this.endPanning&&this.endPanning.call(this,a)};
Grape.fn._scrollMouse=function(a){0!=raceme.wheelValue(a)&&!1==this._current_zooming&&(0<raceme.wheelValue(a)?this.zoomIn():this.zoomOut())};Grape.fn._initDrag=function(a,c,d){if(2!=a.button){var f=this,e=new Grape(document);"undefined"!==typeof c&&(e.touchmove(function(a){a.targetTouches[0]&&c.call(f,a.targetTouches[0])},"dragevents"),e.mousemove(function(a){c.call(f,a)},"dragevents"));e.touchend(function(a){f._endDrag(a,d,e)},"dragevents");e.mouseup(function(a){f._endDrag(a,d,e)},"dragevents")}};
Grape.fn._endDrag=function(a,c,d){d.removeEvent("dragevents");"undefined"!==typeof c&&c.call(this,a)};Grape.fn._onmouseenter=function(a){var c=a.relatedTarget||a.fromElement;if(null!==c&&raceme._contains(a.currentTarget,c))return!1;a=raceme._newEvent("mouse_enter");this.dispatchEvent(a)};
Grape.fn._onmouseleave=function(a){var c=a.toElement||a.relatedTarget;if("undefined"!==typeof c&&null!==c&&raceme._contains(a.currentTarget,c)||null===c&&(a.target||a.srcElement)!=a.currentTarget)return!1;a=raceme._newEvent("mouse_leave");this.dispatchEvent(a)};GenericAnimation=function(){};GenericAnimation.fn=GenericAnimation.prototype;GenericAnimation.fn.constructor=GenericAnimation;GenericAnimation.fn.x=function(a){a=raceme.dV(a,0);this._start(a,Grape.fn.x);return this};
GenericAnimation.fn.y=function(a){a=raceme.dV(a,0);this._start(a,Grape.fn.y);return this};GenericAnimation.fn.move=function(a,c){return this.x(a).y(c)};GenericAnimation.fn.rotate=function(a){a=raceme.dV(a,0);this._start(a,Grape.fn.rotation);return this};GenericAnimation.fn.scale=function(a){a=raceme.dV(a,1);this._start(a,Grape.fn.scale);return this};GenericAnimation.fn.scalex=function(a){a=raceme.dV(a,1);this._start(a,Grape.fn.scalex);return this};
GenericAnimation.fn.scaley=function(a){a=raceme.dV(a,1);this._start(a,Grape.fn.scaley);return this};GenericAnimation.fn.skewx=function(a){a=raceme.dV(a,0);this._start(a,Grape.fn.skewx);return this};GenericAnimation.fn.skewy=function(a){a=raceme.dV(a,0);this._start(a,Grape.fn.skewy);return this};GenericAnimation.fn.topOffset=function(a){a=raceme.dV(a,0);this._start(a,Grape.fn.topOffset);return this};GenericAnimation.fn.scrollTop=function(a){a=raceme.dV(a,0);this._start(a,Grape.fn.scrollTop);return this};
GenericAnimation.fn.fill=function(a){a=raceme.dV(a,0);this._start(a,Grape.fn.fill);return this};GenericAnimation.fn.attr=function(a,c){if("undefined"===typeof a)return this;c=raceme.dV(c,0);this._start(c,Grape.fn.attr,a);return this};GenericAnimation.fn.style=function(a,c){if("undefined"===typeof a)return this;c=raceme.dV(c,0);this._start(c,Grape.fn.style,a);return this};GenericAnimation.fn.opacity=function(a){a=raceme.dV(a,0);a=Math.max(Math.min(a,1),0);return this.style("opacity",a)};
GenericAnimation.fn.width=function(a){return this.attr("width",a)};GenericAnimation.fn.height=function(a){return this.attr("height",a)};GenericAnimation.fn.show=function(){this._start(null,Grape.fn.show)};GenericAnimation.fn.hide=function(){this._start(null,Grape.fn.hide)};GenericAnimation.fn.done=function(a){this._callback=a;return this};GenericAnimation.fn.meanwhile=function(a){this._meanwhile=a;return this};
GenericAnimation.fn.stop=function(){this._next_animation&&this._next_animation.stop();null!==this._interval&&raceme.clearInterval(this._interval);this._interval=null;return this};
GenericAnimation.fn.defrost=function(){if(!0===this._freeze){this._start_time=Date.now()||(new Date).getTime();this._delayed=0;this._finish=this._start_time+this._duration+this._init_delay;this._freeze=!1;for(var a=0;a<this._freezeAnimations.length;a++)this._start(this._freezeAnimations[a].val,this._freezeAnimations[a].fun,this._freezeAnimations[a].attrPassed);this._freezeAnimations=[]}return this};GenericAnimation.fn.frost=function(){this._freeze=!0;return this};
GenericAnimation.fn.animate=function(a,c){var d=new this.constructor(this._grape,a,c);d._freeze=!0;return this._next_animation=d};GenericAnimation.fn.ease=function(a,c){this._easeFunction=raceme._getEaseFunction(a,c);return this};
GenericAnimation.fn.pause=function(a){this._next_animation&&!1===this._next_animation._freeze?this._next_animation.pause(a):!1===this._pause?(this._pause=!0,this._paused_moment=Date.now()||(new Date).getTime(),"undefined"===typeof a?this._is_time_delayed=!1:(this._is_time_delayed=!0,this._delayed+=a)):"undefined"!==typeof a&&(this._is_time_delayed=!0,this._delayed+=a);return this};
GenericAnimation.fn.resume=function(){if(this._next_animation&&!1===this._next_animation._freeze)this._next_animation.resume();else{if(!0===this._pause){var a=(Date.now()||(new Date).getTime())-this._paused_moment;this._finish+=a;this._is_time_delayed=!1}this._pause=!1}return this};GenericAnimation.fn.isPaused=function(){return this._pause?!0:this._next_animation&&!1===this._next_animation._freeze?this._next_animation.isPaused():!1};
GenericAnimation.fn.togglePause=function(){return this.isPaused()?this.resume():this.pause()};
GenericAnimation.fn.restart=function(){this.stop();this._next_animation&&(this._next_animation.frost(),this._next_animation.restart());if(0<this._concurrentAnimations.length){for(var a=[],c=0;c<this._concurrentAnimations.length;c++)a[c]=this._concurrentAnimations[c];this._concurrentAnimations=[];this._start_time=Date.now()||(new Date).getTime();this._delayed=0;this._finish=this._start_time+this._duration+this._init_delay;for(c=0;c<a.length;c++)if(raceme._likeArray(this._grape))for(var d=0;d<this._grape.length;d++)a[c].attrPassed?
a[c].fun.call(this._grape.item(d),a[c].attrPassed,a[c].init_value[d]):a[c].fun.call(this._grape.item(d),a[c].init_value[d]);else a[c].attrPassed?a[c].fun.call(this._grape,a[c].attrPassed,a[c].init_value):a[c].fun.call(this._grape,a[c].init_value);for(c=0;c<a.length;c++)this._start(a[c].val,a[c].fun,a[c].attrPassed)}};
AnimationGroup=function(a,c,d){this._grape=a;this._duration=raceme.dV(c,2E3);this._easeFunction=raceme._getEaseFunction();this._init_delay=raceme.dV(d,0);this._delayed=0;this._is_time_delayed=!1;this._dinterval=Math.min(16,this._duration);this._start_time=Date.now()||(new Date).getTime();this._finish=this._start_time+this._duration+this._init_delay;this._interval=null;this._concurrentAnimations=[];this._freezeAnimations=[];this._pause=this._freeze=!1;this._resume_pause_time=null};
AnimationGroup.prototype=new GenericAnimation;AnimationGroup.fn=AnimationGroup.prototype;AnimationGroup.fn.constructor=AnimationGroup;
AnimationGroup.fn._start=function(a,c,d){if(!1===this._freeze){for(var f=[],e=0;e<this._grape.length;e++)f[e]=d?c.call(this._grape.item(e),d):c.call(this._grape.item(e));for(var h=[],h=raceme._likeArray(a)?a:raceme._filledArray(this._grape.length,a),e=0;e<this._grape.length;e++)"string"===typeof h[e]&&(2<h[e].length&&!1===raceme._getRGB(h[e]))&&(h[e]=raceme._getOperation(f[e],h[e]));a="number";!1!==raceme._getRGB(h[0])&&(a="color");this._concurrentAnimations.push({val:h,fun:c,attrPassed:d,init_value:f,
value_type:a});if(null===this._interval){var g=this;this._interval=raceme.setInterval(function(){g._current_time=Date.now()||(new Date).getTime();if(!1==g._pause){if(g._current_time>g._start_time+g._init_delay+g._delayed){for(var a=1-(g._finish-g._current_time)/g._duration,c=g._easeFunction(a),d=0;d<g._grape.length;d++)for(var e=0;e<g._concurrentAnimations.length;e++){var f=g._concurrentAnimations[e];f.attrPassed?f.fun.call(g._grape.item(d),f.attrPassed,raceme.map(c,0,1,f.init_value[d],f.val[d])):
f.fun.call(g._grape.item(d),raceme.map(c,0,1,f.init_value[d],f.val[d]))}"undefined"!==typeof g._meanwhile&&null!==g._meanwhile&&g._meanwhile.call(g._grape,a,c);if(g._current_time>g._finish){for(d=0;d<g._grape.length;d++)for(e=0;e<g._concurrentAnimations.length;e++)f=g._concurrentAnimations[e],f.attrPassed?f.fun.call(g._grape.item(d),f.attrPassed,f.val[d]):f.fun.call(g._grape.item(d),f.val[d]);raceme.clearInterval(g._interval);g._interval=null;"undefined"!==typeof g._callback&&g._callback.call(g._grape);
g._next_animation instanceof AnimationGroup&&g._next_animation.defrost()}}}else!0==g._is_time_delayed&&g._current_time>g._start_time+g._init_delay+g._delayed&&g.resume()},this._dinterval)}}else this._freezeAnimations.push({val:a,fun:c,attrPassed:d})};GrapeAnimation.prototype=new GenericAnimation;GrapeAnimation.fn=GrapeAnimation.prototype;GrapeAnimation.fn.constructor=GrapeAnimation;
function GrapeAnimation(a,c,d){this._grape=a;this._duration=raceme.dV(c,2E3);this._easeFunction=raceme._getEaseFunction();this._init_delay=raceme.dV(d,0);this._delayed=0;this._is_time_delayed=!1;this._dinterval=Math.min(16,this._duration);this._start_time=Date.now()||(new Date).getTime();this._finish=this._start_time+this._duration+this._init_delay;this._interval=null;this._concurrentAnimations=[];this._freezeAnimations=[];this._pause=this._freeze=!1;this._resume_pause_time=null}
GrapeAnimation.fn._start=function(a,c,d){if(!1===this._freeze){var f;null!==a&&(f=d?c.call(this._grape,d):c.call(this._grape));"string"===typeof a&&(2<a.length&&!1===raceme._getRGB(a))&&(a=raceme._getOperation(f,a));this._concurrentAnimations.push({val:a,fun:c,attrPassed:d,init_value:f,value_type:"number"});if(null===this._interval){var e=this;this._interval=raceme.setInterval(function(){e._current_time=Date.now()||(new Date).getTime();if(!1==e._pause){if(e._current_time>e._start_time+e._init_delay+
e._delayed){for(var a=1-(e._finish-e._current_time)/e._duration,c=e._easeFunction(a),d=0;d<e._concurrentAnimations.length;d++){var f=e._concurrentAnimations[d];null!==f.val&&(f.attrPassed?f.fun.call(e._grape,f.attrPassed,raceme.map(c,0,1,f.init_value,f.val)):f.fun.call(e._grape,raceme.map(c,0,1,f.init_value,f.val)))}"undefined"!==typeof e._meanwhile&&null!==e._meanwhile&&e._meanwhile.call(e._grape,a,c);if(e._current_time>e._finish){for(d=0;d<e._concurrentAnimations.length;d++)f=e._concurrentAnimations[d],
f.attrPassed?f.fun.call(e._grape,f.attrPassed,f.val):f.fun.call(e._grape,f.val);raceme.clearInterval(e._interval);e._interval=null;"undefined"!==typeof e._callback&&e._callback.call(e._grape);e._next_animation instanceof GrapeAnimation&&e._next_animation.defrost()}}}else!0==e._is_time_delayed&&e._current_time>e._start_time+e._init_delay+e._delayed&&e.resume()},this._dinterval)}}else this._freezeAnimations.push({val:a,fun:c,attrPassed:d})};
raceme._execute_main_scripts=function(){raceme.by("svg").style("overflow","hidden");window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame;if("undefined"!==typeof _main_scripts)for(var a=0;a<_main_scripts.length;a++)_main_scripts[a].call(window)};restart=function(){(this instanceof Grape||this instanceof GrapeGroup)&&this.restart()};
raceme._generateId=function(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var d=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==c?d:d&7|8).toString(16)})};
raceme._getEaseFunction=function(a,c){a=raceme.dV(a,"linear");if("linear"==a)return raceme.linear_function;c=raceme.dV(c,"cube");if("inBounce"==a)return raceme.inBounce;if("bounce"==a||"outBounce"==a)return raceme.outBounce;if("inoutBounce"==a)return raceme.inoutBounce;if("sin"==c)return"inout"==a?raceme.inoutSin:"in"==a?raceme.inSin:raceme.outSin;if("quad"==c)return"inout"==a?raceme.inoutQuad:"in"==a?raceme.inQuad:raceme.outQuad;if("cube"==c)return"inout"==a?raceme.inoutCube:"in"==a?raceme.inCube:
raceme.outCube;if("qrt"==c)return"inout"==a?raceme.inoutQrt:"in"==a?raceme.inQrt:raceme.outQrt;if("qnt"==c)return"inout"==a?raceme.inoutQnt:"in"==a?raceme.inQnt:raceme.outQnt;if("expo"==c)return"inout"==a?raceme.inoutExpo:"in"==a?raceme.inExpo:outExpo;if("circ"==c){if("inout"==a)return raceme.inoutCirc;if("in"==a)return raceme.inCirc}return raceme.linear_function};raceme._check=function(a){a=raceme.dV(a,0);return Math.max(0,Math.min(1,a))};raceme.linear_function=function(a){return a=raceme._check(a)};
raceme.inoutSin=function(a){a=raceme._check(a);return-0.5*(Math.cos(Math.PI*a)-1)};raceme.inSin=function(a){a=raceme._check(a);return-Math.cos(a*Math.PI/2)+1};raceme.outSin=function(a){a=raceme._check(a);return Math.sin(a*Math.PI/2)};raceme.inoutQuad=function(a){a=raceme._check(a);return 1>(a/=0.5)?0.5*a*a:-0.5*(--a*(a-2)-1)};raceme.inQuad=function(a){a=raceme._check(a);return a*a};raceme.outQuad=function(a){a=raceme._check(a);return-a*(a-2)};
raceme.inoutCube=function(a){a=raceme._check(a);if(1>(a/=0.5))return 0.5*a*a*a;a-=2;return 0.5*(a*a*a+2)};raceme.inCube=function(a){a=raceme._check(a);return a*a*a};raceme.outCube=function(a){a=raceme._check(a);return--a*a*a+1};raceme.inoutQrt=function(a){a=raceme._check(a);if(1>(a/=0.5))return 0.5*a*a*a*a;a-=2;return-0.5*(a*a*a*a-2)};raceme.inQrt=function(a){a=raceme._check(a);return a*a*a*a};raceme.outQrt=function(a){a=raceme._check(a);return-(--a*a*a*a-1)};
raceme.inoutQnt=function(a){a=raceme._check(a);if(1>(a/=0.5))return 0.5*a*a*a*a*a;a-=2;return 0.5*(a*a*a*a*a+2)};raceme.inQnt=function(a){a=raceme._check(a);return a*a*a*a*a};raceme.outQnt=function(a){a=raceme._check(a);return--a*a*a*a*a+1};raceme.inoutExpo=function(a){a=raceme._check(a);if(1>(a/=0.5))return 0.5*Math.pow(2,10*(a-1));a--;return 0.5*(-Math.pow(2,-10*a)+2)};raceme.inExpo=function(a){a=raceme._check(a);return Math.pow(2,10*(a-1))};
raceme.outExpo=function(a){a=raceme._check(a);return-Math.pow(2,-10*a)+1};raceme.inoutCirc=function(a){a=raceme._check(a);if(1>(a/=0.5))return-0.5*(Math.sqrt(1-a*a)-1)+b;a-=2;return 0.5*(Math.sqrt(1-a*a)+1)};raceme.inCirc=function(a){a=raceme._check(a);return-(Math.sqrt(1-a*a)-1)};raceme.outCirc=function(a){a=raceme._check(a);return Math.sqrt(1- --a*a)};raceme.inBounce=function(a){a=raceme._check(a);return 1-raceme.outBounce(1-a)};
raceme.outBounce=function(a){a=raceme._check(a);return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+0.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+0.9375:7.5625*(a-=2.625/2.75)*a+0.984375};raceme.inoutBounce=function(a){a=raceme._check(a);return 0.5>a?0.5*raceme.inBounce(2*a):0.5*raceme.outBounce(2*a-1)+0.5};raceme._clearString=function(a){"string"!==typeof a&&(a=a.toString());return a.replace(/^\s+|\s+$/g,"").toLowerCase()};
raceme._string2clearArray=function(a,c){for(var d=a.split(c),f=d.length;0<=--f;)d[f]=raceme._clearString(d[f]);return d};raceme._filledArray=function(a,c){for(var d=Array(a);0<=--a;)d[a]=c;return d};raceme._RGBColor=function(a,c,d){this.r=raceme.dV(a,0);this.g=raceme.dV(c,0);this.b=raceme.dV(d,0)};raceme._RGBColor.prototype.getString=function(){return"rgb("+this.r+","+this.g+","+this.b+")"};
raceme._getRGB=function(a){if("string"!==typeof a)return!1;var c=a.replace(/[^\d,]/g,"").split(",");if(3==c.length)return new raceme._RGBColor(parseInt(c[0]),parseInt(c[1]),parseInt(c[2]));c=raceme._hex2rgb(a);return!1!==c?c:!1===isNaN(a)?!1:raceme._getRGB(raceme._name2rgb(a))};raceme._hex2rgb=function(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?new raceme._RGBColor(parseInt(a[1],16),parseInt(a[2],16),parseInt(a[3],16)):!1};
raceme._named_colors={aliceblue:"rgb(240,248,255)",antiquewhite:"rgb(250,235,215)",aqua:"rgb(0,255,255)",aquamarine:"rgb(127,255,212)",azure:"rgb(240,255,255)",beige:"rgb(245,245,220)",bisque:"rgb(255,228,196)",black:"rgb(0,0,0)",blanchedalmond:"rgb(255,235,205)",blue:"rgb(0,0,255)",blueviolet:"rgb(138,43,226)",brown:"rgb(165,42,42)",burlywood:"rgb(222,184,135)",cadetblue:"rgb(95,158,160)",chartreuse:"rgb(127,255,0)",chocolate:"rgb(210,105,30)",coral:"rgb(255,127,80)",cornflowerblue:"rgb(100,149,237)",
cornsilk:"rgb(255,248,220)",crimson:"rgb(220,20,60)",cyan:"rgb(0,255,255)",darkblue:"rgb(0,0,139)",darkcyan:"rgb(0,139,139)",darkgoldenrod:"rgb(184,134,11)",darkgray:"rgb(169,169,169)",darkgreen:"rgb(0,100,0)",darkgrey:"rgb(169,169,169)",darkkhaki:"rgb(189,183,107)",darkmagenta:"rgb(139,0,139)",darkolivegreen:"rgb(85,107,47)",darkorange:"rgb(255,140,0)",darkorchid:"rgb(153,50,204)",darkred:"rgb(139,0,0)",darksalmon:"rgb(233,150,122)",darkseagreen:"rgb(143,188,143)",darkslateblue:"rgb(72,61,139)",
darkslategray:"rgb(47,79,79)",darkslategrey:"rgb(47,79,79)",darkturquoise:"rgb(0,206,209)",darkviolet:"rgb(148,0,211)",deeppink:"rgb(255,20,147)",deepskyblue:"rgb(0,191,255)",dimgray:"rgb(105,105,105)",dimgrey:"rgb(105,105,105)",dodgerblue:"rgb(30,144,255)",firebrick:"rgb(178,34,34)",floralwhite:"rgb(255,250,240)",forestgreen:"rgb(34,139,34)",fuchsia:"rgb(255,0,255)",gainsboro:"rgb(220,220,220)",ghostwhite:"rgb(248,248,255)",gold:"rgb(255,215,0)",goldenrod:"rgb(218,165,32)",gray:"rgb(128,128,128)",
grey:"rgb(128,128,128)",green:"rgb(0,128,0)",greenyellow:"rgb(173,255,47)",honeydew:"rgb(240,255,240)",hotpink:"rgb(255,105,180)",indianred:"rgb(205,92,92)",indigo:"rgb(75,0,130)",ivory:"rgb(255,255,240)",khaki:"rgb(240,230,140)",lavender:"rgb(230,230,250)",lavenderblush:"rgb(255,240,245)",lawngreen:"rgb(124,252,0)",lemonchiffon:"rgb(255,250,205)",lightblue:"rgb(173,216,230)",lightcoral:"rgb(240,128,128)",lightcyan:"rgb(224,255,255)",lightgoldenrodyellow:"rgb(250,250,210)",lightgray:"rgb(211,211,211)",
lightgreen:"rgb(144,238,144)",lightgrey:"rgb(211,211,211)",lightpink:"rgb(255,182,193)",lightsalmon:"rgb(255,160,122)",lightseagreen:"rgb(32,178,170)",lightskyblue:"rgb(135,206,250)",lightslategray:"rgb(119,136,153)",lightslategrey:"rgb(119,136,153)",lightsteelblue:"rgb(176,196,222)",lightyellow:"rgb(255,255,224)",lime:"rgb(0,255,0)",limegreen:"rgb(50,205,50)",linen:"rgb(250,240,230)",magenta:"rgb(255,0,255)",maroon:"rgb(128,0,0)",mediumaquamarine:"rgb(102,205,170)",mediumblue:"rgb(0,0,205)",mediumorchid:"rgb(186,85,211)",
mediumpurple:"rgb(147,112,219)",mediumseagreen:"rgb(60,179,113)",mediumslateblue:"rgb(123,104,238)",mediumspringgreen:"rgb(0,250,154)",mediumturquoise:"rgb(72,209,204)",mediumvioletred:"rgb(199,21,133)",midnightblue:"rgb(25,25,112)",mintcream:"rgb(245,255,250)",mistyrose:"rgb(255,228,225)",moccasin:"rgb(255,228,181)",navajowhite:"rgb(255,222,173)",navy:"rgb(0,0,128)",oldlace:"rgb(253,245,230)",olive:"rgb(128,128,0)",olivedrab:"rgb(107,142,35)",orange:"rgb(255,165,0)",orangered:"rgb(255,69,0)",orchid:"rgb(218,112,214)",
palegoldenrod:"rgb(238,232,170)",palegreen:"rgb(152,251,152)",paleturquoise:"rgb(175,238,238)",palevioletred:"rgb(219,112,147)",papayawhip:"rgb(255,239,213)",peachpuff:"rgb(255,218,185)",peru:"rgb(205,133,63)",pink:"rgb(255,192,203)",plum:"rgb(221,160,221)",powderblue:"rgb(176,224,230)",purple:"rgb(128,0,128)",red:"rgb(255,0,0)",rosybrown:"rgb(188,143,143)",royalblue:"rgb(65,105,225)",saddlebrown:"rgb(139,69,19)",salmon:"rgb(250,128,114)",sandybrown:"rgb(244,164,96)",seagreen:"rgb(46,139,87)",seashell:"rgb(255,245,238)",
sienna:"rgb(160,82,45)",silver:"rgb(192,192,192)",skyblue:"rgb(135,206,235)",slateblue:"rgb(106,90,205)",slategray:"rgb(112,128,144)",slategrey:"rgb(112,128,144)",snow:"rgb(255,250,250)",springgreen:"rgb(0,255,127)",steelblue:"rgb(70,130,180)",tan:"rgb(210,180,140)",teal:"rgb(0,128,128)",thistle:"rgb(216,191,216)",tomato:"rgb(255,99,71)",turquoise:"rgb(64,224,208)",violet:"rgb(238,130,238)",wheat:"rgb(245,222,179)",white:"rgb(255,255,255)",whitesmoke:"rgb(245,245,245)",yellow:"rgb(255,255,0)",yellowgreen:"rgb(154,205,50)"};
raceme._name2rgb=function(a){a=raceme._clearString(a);return"string"===typeof raceme._named_colors[a]?raceme._named_colors[a]:!1};raceme.defaultValue=raceme.dV=function(a,c){return"undefined"!==typeof a?a:c};raceme._defaultAttributeValues={"fill-opacity":1,"stroke-opacity":1,"stroke-width":1,"stroke-miterlimit":4,fill:"rgb(0,0,0)",stroke:"rgb(0,0,0)",opacity:1,x:0,y:0,cx:0,cy:0,width:0,height:0,r:0,rx:0,ry:0,offset:0,"stop-opacity":1,"stop-color":"rgb(0,0,0)"};
raceme._transform2obj=function(a){a=raceme.dV(a,"");a=raceme._clearString(a);a=a.replace(","," ");a=a.replace("\\s+"," ");var c={x:0,y:0,scalex:1,scaley:1,rotation:0,rotationcx:0,rotationcy:0,skewx:0,skewy:0};if(""==a)return c;a=a.split(")");for(var d=0;d<a.length;d++){var f=a[d].split("(");if(2==f.length){f[0]=raceme._clearString(f[0]);f[1]=raceme._clearString(f[1]);var e=f[1].split(" ");"scale"==f[0]?(c.scalex=parseFloat(e[0]),c.scaley=1<e.length?parseFloat(e[1]):c.scalex):"translate"==f[0]?(c.x=
parseFloat(e[0]),1<e.length&&(c.y=parseFloat(e[1]))):"rotate"==f[0]?(c.rotation=parseFloat(e[0]),1<e.length&&(c.rotationcx=parseFloat(e[1])),2<e.length&&(c.rotationcy=parseFloat(e[2]))):"skewX"==f[0]?c.skewx=parseFloat(e[0]):"skewY"==f[0]&&(c.skewy=parseFloat(e[0]))}}return c};
raceme._obj2transform=function(a){var c="";if(0!=a.x||0!=a.y)c+="translate("+a.x+" "+a.y+") ";if(1!=a.scalex||1!=a.scaley)c=a.scaley==a.scalex?c+("scale("+a.scalex+") "):c+("scale("+a.scalex+" "+a.scaley+") ");if(0!=a.rotation||0!=a.rotationcx||0!=a.rotationcy)c+="rotate("+a.rotation+" "+a.rotationcx+" "+a.rotationcy+") ";0!=a.skewx&&(c+="skewX("+a.skewx+") ");0!=a.skewy&&(c+="skewY("+a.skewy+") ");return c};
raceme._likeArray=function(a){return null!==a&&"object"===typeof a&&"number"===typeof a.length?!0:!1};raceme._round=function(a,c){if("undefined"===typeof a)return 0;if("undefined"===typeof c||0==c)return Math.round(a);var d=Math.pow(10,c);return Math.round(a*d)/d};
raceme._mapValues=function(a,c,d,f,e){if(c==d||f==e)return f;var h=!1,g=Math.min(c,d);d=Math.max(c,d);g!=c&&(h=!0);c=!1;var k=Math.min(f,e);e=Math.max(f,e);k!=f&&(c=!0);a=!1==h?(a-g)*(e-k)/(d-g):(d-a)*(e-k)/(d-g);return raceme._round(!1==c?a+k:e-a,3)};raceme._mapValuesUnits=function(a,c,d,f,e){var h=raceme._getUnit(f);return raceme._mapValues(a,c,d,parseFloat(raceme._getVal(f)),parseFloat(raceme._getVal(e))).toString()+h};
raceme._getUnit=function(a){if("string"!==typeof a||2>a.length)return"";if("%"==a.substring(a.length-1))return"%";a=a.substring(a.length-2);return"px"==a||"%"==a||"in"==a||"cm"==a||"mm"==a||"em"==a||"ex"==a||"pt"==a||"pc"==a?a:""};raceme._getVal=function(a){if("string"!==typeof a)return a;var c=raceme._getUnit(a);return a.replace(c,"")};
raceme._getOperation=function(a,c){if("string"===typeof a){var d=raceme._getUnit(a);a=raceme._getVal(a);c=raceme._getVal(c);if(2<c.length){if("+="==c.substring(0,2))return raceme._round(parseFloat(a)+parseFloat(c.substring(2)),3).toString()+d;if("-="==c.substring(0,2))return raceme._round(parseFloat(a)-parseFloat(c.substring(2)),3).toString()+d;if("*="==c.substring(0,2))return raceme._round(parseFloat(a)*parseFloat(c.substring(2)),3).toString()+d;if("/="==c.substring(0,2))return raceme._round(parseFloat(a)/
parseFloat(c.substring(2)),3).toString()+d}return c+d}if(2<c.length){if("+="==c.substring(0,2))return raceme._round(a+parseFloat(c.substring(2)),3);if("-="==c.substring(0,2))return raceme._round(a-parseFloat(c.substring(2)),3);if("*="==c.substring(0,2))return raceme._round(a*parseFloat(c.substring(2)),3);if("/="==c.substring(0,2))return raceme._round(a/parseFloat(c.substring(2)),3)}return""};
raceme._contains=function(a,c){if(a==c)return!0;if("undefined"===typeof c||"undefined"===typeof a)return!1;if(a.contains&&1==c.nodeType)return a.contains(c);if(a.compareDocumentPosition)return 16===a.compareDocumentPosition(c);for(;c&&a!=c;)c=c.parentNode;return c==a};
raceme._mapColors=function(a,c,d,f,e){if(5!=arguments.length)return"rgb(0,0,0)";var h,g;h="string"===typeof f?raceme._getRGB(f):f;g="string"===typeof e?raceme._getRGB(e):e;var k=Math.max(a,c),k=Math.min(k,d),l=Math.round(raceme._mapValues(k,c,d,h.r,g.r)),m=Math.round(raceme._mapValues(k,c,d,h.g,g.g));h=Math.round(raceme._mapValues(k,c,d,h.b,g.b));return(new raceme._RGBColor(l,m,h)).getString()};
raceme.map=function(a,c,d,f,e){if(5!=arguments.length)return"";if("string"===typeof f){if(""!=raceme._getUnit(f))return raceme._mapValuesUnits(a,c,d,f,e);if(!1!==raceme._getRGB(f))return raceme._mapColors(a,c,d,f,e);if(isNaN(parseFloat(f))||isNaN(parseFloat(e)))return""}return raceme._mapValues(a,c,d,f,e)};
raceme._elementPoint=function(a,c,d){var f;return a.ownerSVGElement?(f=a.ownerSVGElement.createSVGPoint(),"undefined"!==typeof c&&"undefined"!==typeof d?(f.x=c,f.y=d):(f.x=a.getBBox().x,f.y=a.getBBox().y),f.matrixTransform(a.getTransformToElement(a.ownerSVGElement))):{x:c,y:d}};raceme._getStyle=function(a){return window.getComputedStyle&&0<window.getComputedStyle(a,null).length?window.getComputedStyle(a,null):a.currentStyle?a.currentStyle:a.style?a.style:{}};
raceme._newEvent=function(a){var c;try{c=new Event(a)}catch(d){c=document.createEvent("Event"),c.initEvent(a,!1,!0)}return c};raceme._area=function(a){return Math.pow(a,2)*Math.PI};raceme._radius=function(a){return Math.sqrt(a/Math.PI)};raceme.polar2rect=function(a,c){var d=a*Math.cos(c*(Math.PI/180)),f=a*Math.sin(c*(Math.PI/180));return{x:d,y:f}};
raceme.rect2polar=function(a,c){var d,f=Math.sqrt(Math.pow(a,2)+Math.pow(c,2));d=0==a?0<c?Math.PI/2:3*Math.PI/2:0>a?Math.atan(c/a)+Math.PI:0>c?Math.atan(c/a)+2*Math.PI:Math.atan(c/a);d*=180/Math.PI;return{r:f,angle:d}};raceme.arc_length=function(a,c){return 2*(c/360)*Math.PI*a};raceme.distance=function(a,c){return Math.sqrt(Math.pow(a.x-c.x,2)+Math.pow(a.y-c.y,2))};
raceme.setInterval=function(a,c){if(window.requestAnimationFrame){var d={running:!0,fn:function(){d.running&&(a.call(),window.requestAnimationFrame(d.fn))}};window.requestAnimationFrame(d.fn);return d}return setInterval(a,c)};raceme.clearInterval=function(a){window.requestAnimationFrame?a.running=!1:clearInterval(a)};raceme.Polygon=function(a){this._area=0;this._points=[];this.length=0;this.max=this.min=null;if("undefined"!==typeof a)for(var c=0;c<a.length;c++)this.add(a[c])};raceme.Polygon.fn=raceme.Polygon.prototype;
raceme.Polygon.fn.item=function(a){-1==a&&(a=this.length-1);a=Math.min(a,this.length-1);a=Math.max(a,0);return this._points[a]};raceme.Polygon.fn.add=function(a){this._points.push(a);this.length++;null===this.min?(this.min={x:a.x,y:a.y},this.max={x:a.x,y:a.y}):(this.min.x=Math.min(this.min.x,a.x),this.min.y=Math.min(this.min.y,a.y),this.max.x=Math.max(this.max.x,a.x),this.max.y=Math.max(this.max.y,a.y));return this};
raceme.Polygon.fn.area=function(){var a,c,d=0;for(a=0;a<this.length;a++)c=(a+1)%this.length,d+=this.item(a).x*this.item(c).y,d-=this.item(a).y*this.item(c).x;d/=2;return 0>d?-d:d};raceme.Polygon.fn.centroid=function(){var a,c;c=this.length-1;var d=0,f=0;for(a=0;a<this.length;a++){var e=this.item(a),h=this.item(c);c=e.x*h.y-h.x*e.y;d+=(e.x+h.x)*c;f+=(e.y+h.y)*c;c=a}c=6*this.area();a={x:d/c,y:f/c};return!1==this.pointInside(a)&&(d=this.innerCentroid(),null!==d)?d:a};
raceme.Polygon.fn.innerCentroid=function(a){"undefined"===typeof a&&(a=20);for(var c=(this.max.y-this.min.y)/a,d=(this.max.x-this.min.x)/a,f=null,e=null,h=null,g=0;g<a;g++)for(var k=0;k<a;k++){var l=this.min.x+(d/2+g*d),m=this.min.y+(c/2+k*c);this.pointInside({x:l,y:m})&&(null===f||this.sumDistancefromBorders({x:l,y:m})<f)&&(f=this.sumDistancefromBorders({x:l,y:m}),e=g,h=k)}return null===e?null:{x:this.min.x+(d/2+e*d),y:this.min.y+(c/2+h*c)}};
raceme.Polygon.fn.sumDistancefromBorders=function(a){for(var c=0,d=0;d<this.length;d++)c+=raceme.distance(a,this.item(d));return c};raceme.Polygon.fn.pointInside=function(a){for(var c=!1,d=0,f=this.length-1;d<this.length;f=d++){var e=this.item(d).x,h=this.item(d).y,g=this.item(f).x,f=this.item(f).y;h>a.y!=f>a.y&&a.x<(g-e)*(a.y-h)/(f-h)+e&&(c=!c)}return c};
"complete"===document.readyState?raceme._execute_main_scripts():document.addEventListener?document.addEventListener("DOMContentLoaded",raceme._execute_main_scripts,!1):document.attachEvent&&document.attachEvent("onreadystatechange",raceme._execute_main_scripts);
